#!/bin/bash

#PBS -lwalltime=08:00:00
#PBS -lselect=1:ncpus=8:mem=32gb

#PBS -N 0201_900-101

cd $PBS_O_WORKDIR

module purge
module load tools/prod
module load GROMACS/2021.5-foss-2021b

# Define file names
name="0201"
ratio="900-101"
folder1="Lambda"
folder2="Lambda/${name}"
folder3="Lambda/${name}/${ratio}"
lambda_output_folder="${folder3}/Lambda_Files"

input_structure="${folder3}/CG_WAT_TEA_${ratio}.pdb"
input_topology="${folder3}/mixtop_${ratio}.top"
minimisation_mdp="${folder1}/minim.mdp"
nvt_mdp="${folder1}/nvt.mdp"
npt_mdp="${folder1}/npt.mdp"
prod_run_mdp="${folder3}/lambda.mdp"
output_directory="${folder3}/Other_Outputs"
output_structure="${output_directory}/output.gro"
output_tpr="${output_directory}/output.tpr"

# Ensure output directory exists
mkdir -p ${output_directory}

# Log files for capturing command output and errors
log_file="${output_directory}/gromacs_workflow_HPC.log"
err_file="${output_directory}/gromacs_workflow_HPC.err"
echo "Logging to ${log_file} and ${err_file}"

# Step 1: Energy Minimisation
echo "Running energy minimisation..."
gmx grompp -f ${minimisation_mdp} -c ${input_structure} -p ${input_topology} -o ${output_directory}/em.tpr 
mpirun gmx_mpi mdrun -v -deffnm ${output_directory}/em 

# Step 2: NVT
echo "Running NVT..."
gmx grompp -f ${nvt_mdp} -c ${output_directory}/em.gro -p ${input_topology} -o ${output_directory}/nvt.tpr 
mpirun gmx_mpi mdrun -v -deffnm ${output_directory}/nvt -dlb yes

# Step 3: NPT
echo "Running NPT..."
gmx grompp -f ${npt_mdp} -c ${output_directory}/nvt.gro -p ${input_topology} -o ${output_directory}/npt.tpr 
mpirun gmx_mpi mdrun -v -deffnm ${output_directory}/npt -dlb yes

echo "Extracting energy, pressure, and volume data from npt.edr"
# Define input energy file
energy_file="${output_directory}/npt.edr"
# Define output files
energy_output="${output_directory}/npt_energy_${name}.xvg"
pressure_output="${output_directory}/npt_pressure_${name}.xvg"
volume_output="${output_directory}/npt_volume_${name}.xvg"
density_output="${output_directory}/npt_density_${name}.xvg"

# Extract Energy
echo 1 4 5 6 8 | gmx energy -f ${energy_file} -o ${energy_output}
# Extract Pressure
echo "Pressure" | gmx energy -f ${energy_file} -o ${pressure_output} 
# Extract Volume
echo "Volume" | gmx energy -f ${energy_file} -o ${volume_output} 
# Extract Density
echo "Density" | gmx energy -f ${energy_file} -o ${density_output} 


# Start For Loop Here
for i in {0..14}; do

  # Step 4: Lambda Run
  echo "Running Lambda Run for lambda state ${i}..."
  # Update the lambda state in the mdp file
  sed -i "s/init-lambda-state *= *[0-9]*/init-lambda-state = ${i}/" ${prod_run_mdp}

  gmx grompp -f ${prod_run_mdp} -c ${output_directory}/npt.gro -p ${input_topology} -o ${lambda_output_folder}/lambda_${i}.tpr
  mpirun gmx_mpi mdrun -v -deffnm ${lambda_output_folder}/lambda_${i} -dlb yes

  echo "Extracting energy, pressure, and volume data from lambda.edr"
  # Define input energy file
  energy_file="${lambda_output_folder}/lambda_${i}.edr"
  # Define output files
  energy_output="${lambda_output_folder}/lambda_energy_${i}.xvg"
  pressure_output="${lambda_output_folder}/lambda_pressure_${i}.xvg"
  volume_output="${lambda_output_folder}/lambda_volume_${i}.xvg"
  density_output="${lambda_output_folder}/lambda_density_${i}.xvg" 
  enthalpy_output="${lambda_output_folder}/lambda_enthalpy_${i}.xvg" 

  # Extract Energy
  echo 1 4 5 6 7 | gmx energy -f ${energy_file} -o ${energy_output}
  # Extract Pressure
  echo "Pressure" | gmx energy -f ${energy_file} -o ${pressure_output} 
  # Extract Volume
  echo "Volume" | gmx energy -f ${energy_file} -o ${volume_output} 
  # Extract Density
  echo "Density" | gmx energy -f ${energy_file} -o ${density_output} 
  # Extract Enthalpy
  echo "Enthalpy" | gmx energy -f ${energy_file} -o ${enthalpy_output} 

  echo "Extraction completed successfully for lambda state ${i}."

done

gmx bar -f ${lambda_output_folder}/lambda_0.xvg ${lambda_output_folder}/lambda_1.xvg ${lambda_output_folder}/lambda_2.xvg ${lambda_output_folder}/lambda_3.xvg ${lambda_output_folder}/lambda_4.xvg ${lambda_output_folder}/lambda_5.xvg ${lambda_output_folder}/lambda_6.xvg ${lambda_output_folder}/lambda_7.xvg ${lambda_output_folder}/lambda_8.xvg ${lambda_output_folder}/lambda_9.xvg ${lambda_output_folder}/lambda_10.xvg ${lambda_output_folder}/lambda_11.xvg ${lambda_output_folder}/lambda_12.xvg ${lambda_output_folder}/lambda_13.xvg ${lambda_output_folder}/lambda_14.xvg -o ${folder3}/bar.xvg -oi ${folder3}/barint.xvg -oh ${folder3}/histo.xvg -prec 8
